"""add_performance_indexes

Revision ID: 61f534cf5428
Revises: 4f1b54d6a2fa
Create Date: 2026-01-26 15:02:33.205358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61f534cf5428'
down_revision: Union[str, None] = '4f1b54d6a2fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Performance indexes for faster queries
    op.create_index('ix_question_category', 'question', ['category'], unique=False)
    op.create_index('ix_question_difficulty', 'question', ['difficulty'], unique=False)
    op.create_index('ix_question_school', 'question', ['school_id'], unique=False)
    op.create_index('ix_question_school_category', 'question', ['school_id', 'category'], unique=False)
    op.create_index('ix_quiz_attempt_finished_at', 'quiz_attempt', ['finished_at'], unique=False)
    op.create_index('ix_quiz_attempt_quiz', 'quiz_attempt', ['quiz_id'], unique=False)
    op.create_index('ix_quiz_attempt_room_member', 'quiz_attempt', ['room_member_id'], unique=False)
    op.create_index('ix_quiz_room', 'quizze', ['room_id'], unique=False)
    op.create_index('ix_quiz_school', 'quizze', ['school_id'], unique=False)
    op.create_index('ix_quiz_school_dates', 'quizze', ['school_id', 'starts_at', 'ends_at'], unique=False)
    op.create_index('ix_quiz_starts_at', 'quizze', ['starts_at'], unique=False)
    op.create_index('ix_quiz_template', 'quizze', ['template_id'], unique=False)
    op.create_index('ix_room_school', 'room', ['school_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_room_school', table_name='room')
    op.drop_index('ix_quiz_template', table_name='quizze')
    op.drop_index('ix_quiz_starts_at', table_name='quizze')
    op.drop_index('ix_quiz_school_dates', table_name='quizze')
    op.drop_index('ix_quiz_school', table_name='quizze')
    op.drop_index('ix_quiz_room', table_name='quizze')
    op.drop_index('ix_quiz_attempt_room_member', table_name='quiz_attempt')
    op.drop_index('ix_quiz_attempt_quiz', table_name='quiz_attempt')
    op.drop_index('ix_quiz_attempt_finished_at', table_name='quiz_attempt')
    op.drop_index('ix_question_school_category', table_name='question')
    op.drop_index('ix_question_school', table_name='question')
    op.drop_index('ix_question_difficulty', table_name='question')
    op.drop_index('ix_question_category', table_name='question')
    # ### end Alembic commands ###
