"""added necessary tables

Revision ID: ef1549aace2e
Revises: ab4ddc8f48f7
Create Date: 2025-11-30 16:55:58.234950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef1549aace2e'
down_revision: Union[str, None] = 'ab4ddc8f48f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('actor_type', sa.Enum('SCHOOL_STAFF', 'SYSTEM', 'API', name='audit_actor_type'), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_action', 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_actor', 'audit_logs', ['actor_type', 'actor_id'], unique=False)
    op.create_table('file_storage_records',
    sa.Column('owner_type', sa.String(length=50), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('size', sa.BigInteger(), nullable=True),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_file_owner', 'file_storage_records', ['owner_type', 'owner_id'], unique=False)
    op.create_table('notifications',
    sa.Column('recipient_type', sa.Enum('STUDENT', 'STAFF', 'SYSTEM', name='notification_recipient'), nullable=False),
    sa.Column('recipient_id', sa.UUID(), nullable=True),
    sa.Column('notification_type', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notification_recipient', 'notifications', ['recipient_type', 'recipient_id'], unique=False)
    op.create_table('plans',
    sa.Column('name', sa.Enum('FREE', 'BASIC', 'PREMIUM', name='plan_tier'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('monthly_price_cents', sa.Integer(), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('limits', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('system_settings',
    sa.Column('rousseau_reference_version', sa.String(length=50), nullable=True),
    sa.Column('default_language', sa.String(length=10), nullable=True),
    sa.Column('global_limits', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('allowed_file_types', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schools',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=True),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('timezone', sa.String(length=100), nullable=True),
    sa.Column('locale', sa.String(length=50), nullable=True),
    sa.Column('language_defaults', sa.String(length=50), nullable=True),
    sa.Column('plan_id', sa.UUID(), nullable=True),
    sa.Column('billing_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_number', name='uq_schools_registration')
    )
    op.create_index('ix_schools_plan_id', 'schools', ['plan_id'], unique=False)
    op.create_table('ai_analysis_jobs',
    sa.Column('school_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='ai_analysis_status'), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('cost_estimate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_jobs_school', 'ai_analysis_jobs', ['school_id'], unique=False)
    op.create_table('ocr_jobs',
    sa.Column('school_id', sa.UUID(), nullable=True),
    sa.Column('file_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='ocr_job_status'), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['file_storage_records.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ocr_school', 'ocr_jobs', ['school_id'], unique=False)
    op.create_table('staff_users',
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'INSTRUCTOR', 'SECRETARY', name='staff_role'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_staff_email', 'staff_users', ['email'], unique=True)
    op.create_index('ix_staff_school', 'staff_users', ['school_id'], unique=False)
    op.create_table('question_bank_questions',
    sa.Column('school_id', sa.UUID(), nullable=True),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', name='question_difficulty'), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_image_path', sa.String(length=500), nullable=True),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('correct_option_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('is_multiple_choice', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['staff_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_qbq_category', 'question_bank_questions', ['category'], unique=False)
    op.create_index('ix_qbq_difficulty', 'question_bank_questions', ['difficulty'], unique=False)
    op.create_index('ix_qbq_school', 'question_bank_questions', ['school_id'], unique=False)
    op.create_table('quiz_templates',
    sa.Column('school_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('total_time_seconds', sa.Integer(), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('visibility', sa.String(length=50), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['staff_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_quiz_templates_school', 'quiz_templates', ['school_id'], unique=False)
    op.create_table('rooms',
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['staff_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'code', name='uq_rooms_school_code')
    )
    op.create_index('ix_rooms_school', 'rooms', ['school_id'], unique=False)
    op.create_table('students',
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('student_code', sa.String(length=50), nullable=False),
    sa.Column('national_id', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('profile_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['staff_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'student_code', name='uq_students_school_code')
    )
    op.create_index('ix_students_school', 'students', ['school_id'], unique=False)
    op.create_table('quiz_template_questions',
    sa.Column('quiz_template_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('question_order', sa.Integer(), nullable=False),
    sa.Column('override_score', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question_bank_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quiz_template_id'], ['quiz_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quiz_template_id', 'question_id', name='uq_template_question')
    )
    op.create_index('ix_template_questions_order', 'quiz_template_questions', ['quiz_template_id', 'question_order'], unique=False)
    op.create_table('room_quiz_instances',
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('quiz_template_id', sa.UUID(), nullable=False),
    sa.Column('instance_settings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['staff_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['quiz_template_id'], ['quiz_templates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_room_quiz_room', 'room_quiz_instances', ['room_id'], unique=False)
    op.create_index('ix_room_quiz_template', 'room_quiz_instances', ['quiz_template_id'], unique=False)
    op.create_table('student_room_memberships',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'REMOVED', name='room_membership_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'room_id', name='uq_student_room')
    )
    op.create_table('quiz_attempts',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('room_quiz_instance_id', sa.UUID(), nullable=True),
    sa.Column('quiz_template_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'SUBMITTED', 'GRADED', name='quiz_attempt_status'), nullable=False),
    sa.Column('answer_payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('score_value', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['quiz_template_id'], ['quiz_templates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_quiz_instance_id'], ['room_quiz_instances.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_quiz_attempt_room_instance', 'quiz_attempts', ['room_quiz_instance_id'], unique=False)
    op.create_index('ix_quiz_attempt_student', 'quiz_attempts', ['student_id'], unique=False)
    op.create_index('ix_quiz_attempt_template', 'quiz_attempts', ['quiz_template_id'], unique=False)
    op.create_table('question_attempts',
    sa.Column('quiz_attempt_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('chosen_option_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question_bank_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quiz_attempt_id'], ['quiz_attempts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_question_attempts_question', 'question_attempts', ['question_id'], unique=False)
    op.create_index('ix_question_attempts_quiz', 'question_attempts', ['quiz_attempt_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_question_attempts_quiz', table_name='question_attempts')
    op.drop_index('ix_question_attempts_question', table_name='question_attempts')
    op.drop_table('question_attempts')
    op.drop_index('ix_quiz_attempt_template', table_name='quiz_attempts')
    op.drop_index('ix_quiz_attempt_student', table_name='quiz_attempts')
    op.drop_index('ix_quiz_attempt_room_instance', table_name='quiz_attempts')
    op.drop_table('quiz_attempts')
    op.drop_table('student_room_memberships')
    op.drop_index('ix_room_quiz_template', table_name='room_quiz_instances')
    op.drop_index('ix_room_quiz_room', table_name='room_quiz_instances')
    op.drop_table('room_quiz_instances')
    op.drop_index('ix_template_questions_order', table_name='quiz_template_questions')
    op.drop_table('quiz_template_questions')
    op.drop_index('ix_students_school', table_name='students')
    op.drop_table('students')
    op.drop_index('ix_rooms_school', table_name='rooms')
    op.drop_table('rooms')
    op.drop_index('ix_quiz_templates_school', table_name='quiz_templates')
    op.drop_table('quiz_templates')
    op.drop_index('ix_qbq_school', table_name='question_bank_questions')
    op.drop_index('ix_qbq_difficulty', table_name='question_bank_questions')
    op.drop_index('ix_qbq_category', table_name='question_bank_questions')
    op.drop_table('question_bank_questions')
    op.drop_index('ix_staff_school', table_name='staff_users')
    op.drop_index('ix_staff_email', table_name='staff_users')
    op.drop_table('staff_users')
    op.drop_index('ix_ocr_school', table_name='ocr_jobs')
    op.drop_table('ocr_jobs')
    op.drop_index('ix_ai_jobs_school', table_name='ai_analysis_jobs')
    op.drop_table('ai_analysis_jobs')
    op.drop_index('ix_schools_plan_id', table_name='schools')
    op.drop_table('schools')
    op.drop_table('system_settings')
    op.drop_table('plans')
    op.drop_index('ix_notification_recipient', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_file_owner', table_name='file_storage_records')
    op.drop_table('file_storage_records')
    op.drop_index('ix_audit_actor', table_name='audit_logs')
    op.drop_index('ix_audit_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
